server:
  port: 9296

spring:
  application:
    name: CONFIG-SERVER
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Dawud18854/config-server
          clone-on-start: true

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
