server:
  port: 9191

spring:
  cloud:
    gateway:
      routes:
        - id: USER-SERVICE
          uri: lb://USER-SERVICE
          predicates:
          - Path=/users/**
          filters:
          - RewritePath=/(?<path>.*), /$\{path}
          - name: CircuitBreaker
            args:
              name: USER-SERVICE
              fallbackUri: forward:/fallback/userServiceFallBack
        - id: DEPARTMENT-SERVICE
          uri: lb://DEPARTMENT-SERVICE
          predicates:
          - Path=/departments/**
          filters:
          - RewritePath=/(?<path>.*), /$\{path}
          - name: CircuitBreaker
            args:
              name: DEPARTMENT-SERVICE
              fallbackUri: forward:/fallback/departmentServiceFallBack
        - id: ASSIGNMENT-SERVICE
          uri: lb://ASSIGNMENT-SERVICE
          predicates:
          - Path=/assignments/**
          filters:
          - RewritePath=/(?<path>.*), /$\{path}
          - name: CircuitBreaker
            args:
              name: ASSIGNMENT-SERVICE
              fallbackUri: forward:/fallback/assignmentServiceFallBack

resilience4j:
  circuitbreaker:
    configs:
      default:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 5s
        failureRateThreshold: 50
        eventConsumerBufferSize: 10
        recordExceptions:
          - org.springframework.web.client.HttpServerErrorException
          - java.util.concurrent.TimeoutException
          - java.io.IOException
          - java.net.ConnectException
    instances:
      department-service:
        baseConfig: default
      user-service:
        baseConfig: default
      assignment-service:
        baseConfig: default