server:
  port: 9191

spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: USER-SERVICE
          uri: lb://USER-SERVICE
          predicates:
            - Path=/users/**
          filters:
            - name: CIRCUIT-BREAKER
              args:
                name: USER-CIRCUIT-BREAKER
                fallbackUri: forward:/userServiceFallBack
        - id: DEPARTMENT-SERVICE
          uri: lb://DEPARTMENT-SERVICE
          predicates:
              - Path=/departments/**
        - id: ASSIGNMENT-SERVICE
          uri: lb://ASSIGNMENT-SERVICE
          predicates:
            - Path=/assignments/**
