server:
  port: 9191

spring:
  cloud:
    gateway:
      routes:
        - id: USER-SERVICE
          uri: lb://USER-SERVICE
          predicates:
            - Path=/users/**
          filters:
          - RewritePath=/users/(?<path>.*), /$\{path}
        - id: DEPARTMENT-SERVICE
          uri: lb://DEPARTMENT-SERVICE
          predicates:
              - Path=/departments/**
        - id: ASSIGNMENT-SERVICE
          uri: lb://ASSIGNMENT-SERVICE
          predicates:
            - Path=/assignments/**
